### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by numairawan** [AlttiRi/meganz-api#1]
Hi, Can i login and upload using this?

**Comment by AlttiRi** [comment]
No, it's not implemented.

I recommend to use https://github.com/qgustavor/mega

---

As the readme says

> **Uncomplited**, backlogged Mega.nz JS library.

Currently, I'm not going to complete this library (add new functions, or docs).

But anyway it's working, it supports listing, thumbs/previews downloading.

I use it here:
https://alttiri.github.io/file-manager-snapshot-explorer/
You can put a mega URL in the search field to see the work. For example, 
```
https://mega.nz/folder/ZuoWSDoC#ODTEJaqcIxj8IRfBT0E-vw
```
 (taken from https://twitter.com/fazalabul/status/1580905827086438400)

At the moment when I have written this lib (2020) no one library (except the official one, used on the site) did not support thumbs/previews downloading.

---

Well, I need to make the readme more informative about the nature of this repo.

**Comment by numairawan** [comment]
Alright thanks.
